### ISSUE TITLE
Error on hover

### ISSUE THREAD

**Issue by Kizmar** [cr4ckp0t/ElvUI_CorruptionDatatext#1]
Message: ...ace\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua:141: attempt to index global 'CorruptionTooltips' (a nil value)
Time: Tue Jun 30 10:31:23 2020
Count: 3
Stack: ...ace\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua:141: attempt to index global 'CorruptionTooltips' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua"]:141: in function `GetItemCorruption'
[string "@Interface\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua"]:167: in function <...ace\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua:154>
[string "@Interface\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua"]:221: in function `onEnter'
[string "@Interface\AddOns\ElvUI\Modules\datatexts\DataTexts.lua"]:222: in function <...terface\AddOns\ElvUI\Modules\datatexts\DataTexts.lua:220>

Locals:

**Comment by cr4ckp0t** [comment]
Sorry about that. Fixed in 1.1.1.
