### ISSUE TITLE
Now getting this on 1.1.1 :) 

### ISSUE THREAD

**Issue by Kizmar** [cr4ckp0t/ElvUI_CorruptionDatatext#2]
Message: ...ace\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua:222: bad argument #1 to 'format' (string expected, got nil)
Time: Tue Jun 30 11:31:18 2020
Count: 1
Stack: ...ace\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua:222: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\ElvUI_CorruptionDT\ElvUI_CorruptionDT.lua"]:222: in function `onEnter'
[string "@Interface\AddOns\ElvUI\Modules\datatexts\DataTexts.lua"]:222: in function <...terface\AddOns\ElvUI\Modules\datatexts\DataTexts.lua:220>

**Comment by Kizmar** [comment]
By the way, thank you for taking the time to write this add-on!

**Comment by cr4ckp0t** [comment]
It will take some debugging, which I cannot do at work. Once I get home I will fix it and push it to Curse. Thanks for the heads up!

**Comment by cr4ckp0t** [comment]
Okay, I have it fixed and working in version 1.1.2. Sorry about that.

**Comment by Kizmar** [comment]
Confirmed! Thank you!
